version: '3.9'

services:
  nginx:
    container_name: ${APP_NAME}_nginx
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - php
    volumes:
      - ./:/var/www/html
      - ./docker/logs/nginx:/var/log/nginx

  db:
    container_name: ${APP_NAME}_db
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: init
    ports:
      - '15432:5432'

  php:
    container_name: ${APP_NAME}_php
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    depends_on:
      - db
    volumes:
      - ./:/var/www/html/
      - ./docker/logs/php.log:/var/log/fpm-php.www.log
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini