version: '3.9'

services:
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "80:80"
    networks:
      - internal
    volumes:
      - ./:/var/www/html
      - ./docker/logs/nginx:/var/log/nginx

  php:
    container_name: php
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    networks:
      - internal
    volumes:
      - ./:/var/www/html/
      - ./docker/logs/php.log:/var/log/fpm-php.www.log
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini

networks:
  internal:
    driver: bridge